name: Scrape

on:
  workflow_dispatch:
    inputs:
      accountsToScrape:
        default: ""
        required: false
        description: "Accounts to scrape (comma separated)"
      daysBack:
        default: "10"
        required: false
        description: "Days back to scrape"
      worksheetName:
        default: "ExpensesReport"
        required: false
        description: "The name of the worksheet to write to"
  schedule:
    - cron: "33 10 * * */2"
env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}:latest
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Pull image
        run: docker pull $IMAGE_NAME
      - name: Run scraper
        run: docker run --rm
          -e DEBUG
          -e DAYS_BACK
          -e TZ
          -e WORKSHEET_NAME
          -e ACCOUNTS_JSON
          -e TELEGRAM_API_KEY
          -e TELEGRAM_CHAT_ID
          -e GOOGLE_SHEET_ID
          -e GOOGLE_SERVICE_ACCOUNT_EMAIL
          -e GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY
          -e ACCOUNTS_TO_SCRAPE
          -e ADE_DATABASE_NAME
          -e ADE_TABLE_NAME
          -e ADE_INGESTION_MAPPING
          -e ADE_INGEST_URI
          -e AZURE_TENANT_ID
          -e AZURE_APP_ID
          -e AZURE_APP_KEY
          $IMAGE_NAME
        env:
          DEBUG: ""
          TZ: "Asia/Jerusalem"
          DAYS_BACK: ${{ github.event.inputs.daysBack }}
          WORKSHEET_NAME: ${{ github.event.inputs.worksheetName }}
          ACCOUNTS_TO_SCRAPE: ${{ github.event.inputs.accountsToScrape }}
          ACCOUNTS_JSON: ${{ secrets.ACCOUNTS_JSON }}
          TELEGRAM_API_KEY: ${{ secrets.TELEGRAM_API_KEY }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
          GOOGLE_SERVICE_ACCOUNT_EMAIL: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}
          GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY }}
          ADE_DATABASE_NAME: ${{ secrets.ADE_DATABASE_NAME }}
          ADE_TABLE_NAME: ${{ secrets.ADE_TABLE_NAME }}
          ADE_INGESTION_MAPPING: ${{ secrets.ADE_INGESTION_MAPPING }}
          ADE_INGEST_URI: ${{ secrets.ADE_INGEST_URI }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_APP_ID: ${{ secrets.AZURE_APP_ID }}
          AZURE_APP_KEY: ${{ secrets.AZURE_APP_KEY }}
